services:
  back:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always

  proxy:
    image: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/skud_app.conf
    restart: always
    depends_on:
      - back

  # front:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile.front
  #   restart: always
  #   depends_on: 
  #     - proxy
  #   ports:
  #     - "3000:3000"